name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint 'src/**'

      - name: Run tests
        run: npm run test:ci

      - name: Generate Coveralls Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
